Adding Daily percentage classes
OryJonay/Odds-Gym pull request #5
Opened 2020-04-11 14:13 UTC by dgingi

2020-04-11 14:14 UTC, dgingi commented
@OryJonay Please take a look at my last 2 commits and approve the changes

2020-04-11 14:45 UTC, OryJonay requested changes
I'll fix the comment about the aligning the "for", add ThreeWaySoccerPercentageEnv and do another go on the docs.

2020-04-11 14:45 UTC, OryJonay commented on oddsgym/envs/base.py
> +        zero_rows_count = numpy.sum(~results.any(1))
Nice :-)

2020-04-11 14:45 UTC, OryJonay commented on oddsgym/envs/daily_bets.py
> +                                                            for i in numpy.arange(self.action_space.shape[0])]))
The "for" needs to be aligned with the inner brackets (just FYI)

2020-04-13 14:49 UTC, OryJonay requested changes
@dgingi Please review my latest commit and add more cases to the "test_step" of the new soccer environments.

2020-04-13 14:49 UTC, OryJonay commented on tests/test_three_way_daily_percentage_env.py
> +    assert three_way_daily_percentage_env.current_step == 1
Add more cases

2020-04-13 14:49 UTC, OryJonay commented on tests/test_three_way_daily_env.py
> +    assert three_way_daily_env.current_step == 1
Add more cases

2020-04-15 15:02 UTC, merged